pipeline {
    agent {
        label 'agent1'
    }
    tools {
        jdk 'jdk'
        nodejs 'nodejs'
    }
    environment  {
        SCANNER_HOME=tool 'sonar-scanner'
    }
    stages {
        stage('Cleaning Workspace') {
            steps {
                cleanWs()
            }
        }
        stage('Checkout from Git') {
            steps {
                git credentialsId:'MyID',url:'https://github.com/PriyeshPandey07/sonarqube-pipeline-project.git',branch:'jenkinssonar'
            }
        }
        stage('Sonarqube Analysis') {
            steps {
                dir('src/frontend') {
                    withSonarQubeEnv('sonar-server') {
                        sh ''' $SCANNER_HOME/bin/sonar-scanner \
                        -Dsonar.projectName=sonar-jenkins-project \
                        -Dsonar.projectKey=sonar-jenkins-project'''
                    }
                }
            }
        }
        stage('QualityGate') {
            steps {
                script {
                    waitForQualityGate abortPipeline: false, credentialsId: 'sonartoken' 
                }
            }
        }
        stage('OWASP Scan') {
            steps {
                dir('src/frontend') {
                    dependencyCheck additionalArguments: '--scan ./ --disableYarnAudit --disableNodeAudit', odcInstallation: 'DP-CHECK'
                    dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
                }
            }
        }
        stage('TrivyFScan') {
            steps {
                dir('src/frontend') {
                    sh 'trivy fs . > trivyfs.txt'
                }
            }
        }
        stage("Image Create") {
            steps {
                script {
                    dir('src/frontend') {
                            sh 'docker build -t sonarci .'
                    }
                }
            }
        }
        stage("ImagePush") {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'docker-creds-repo', usernameVariable: 'docker_user', passwordVariable: 'docker_pass')]) {
                    sh "docker tag sonarci ${env.docker_user}/sonarci:${BUILD_NUMBER}"
                    sh "docker login -u ${env.docker_user} -p ${env.docker_pass}"
                    sh "docker push ${env.docker_user}/sonarci:${BUILD_NUMBER}"
                    }
                }
            }
        }
        stage("ImageScan") {
            steps {
                sh 'trivy image prateekkumawat/sonarci:${BUILD_NUMBER} > trivyimage_${BUILD_NUMBER}.txt' 
            }
        }
    }
}